"""Preparation code. This code was not generated by the LLM."""
import os

__location__ = os.path.realpath(os.path.join(os.getcwd(), os.path.dirname(__file__)))
input_file   = os.path.join(__location__,"input.txt")

"""
--------------------------------------------------------------------------------
Solving Advent of Code with Large Language Model
Following input was entered to https://huggingface.co/bigscience/bloom
--------------------------------------------------------------------------------
Generation of text input for LLM: 3
Generation to get a working code: 9
Note: I also forced the LLM to generate comments when I had working code.
--------------------------------------------------------------------------------
Input for LLM as follows:
--------------------------------------------------------------------------------
Task:
- define an empty list called "elves"
- open an input text file and read it line by line
  - if the line is int, add it to the temp variable
  - if an empty line is found, append total_cal to list  "elves" and reset total_cal to 0
- find the highest value in the list "elves" and print it

Python code solution:
"""

with open(input_file) as f:  # open the input file
    total_cal = 0  # the total amount of calories stored in the list
    elves = []  # define an empty list to store the highest value
    for line in f:  # read the input file line by line
        try:  # try to convert the input line to int
            total_cal += int(line)
        except ValueError:  # if the line could not be converted to an int,
            elves.append(total_cal)  # append total_cal to the elves list
            total_cal = 0  # reset total_cal to 0
    print(max(elves))  # print the highest value in the list "elves"